name: Backend CI

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'server/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - name: Install dependencies
        run: |
          cd server
          go mod tidy

      - name: Run tests
        run: |
          cd server
          go test -v ./...

      - name: Run linter
        run: |
          cd server
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          golangci-lint run

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test-and-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Deploying backend to production..."
          # Add your backend deployment script here
